"""
Django settings for SAC WEB project.
Sistema de Administración de Condominio

Generated by 'django-admin startproject' using Django 6.0.1.
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


import os
from dotenv import load_dotenv

load_dotenv()

# =============================================================================
# CONFIGURACIÓN DE SEGURIDAD
# =============================================================================

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'dummy-secret-key-for-dev')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

# En desarrollo dejamos ALLOWED_HOSTS vacío
# Django permite localhost y 127.0.0.1 automáticamente cuando DEBUG=True
ALLOWED_HOSTS = []


# =============================================================================
# APLICACIONES INSTALADAS
# =============================================================================
# Aquí registramos todas las aplicaciones que usa el proyecto.
# Las primeras 6 son de Django (vienen incluidas).
# 'nucleo' es nuestra aplicación principal del sistema SAC WEB.

INSTALLED_APPS = [
    'django.contrib.admin',         # Panel de administración
    'django.contrib.auth',          # Sistema de autenticación
    'django.contrib.contenttypes',  # Tipos de contenido
    'django.contrib.sessions',      # Manejo de sesiones
    'django.contrib.messages',      # Mensajes flash
    'django.contrib.staticfiles',   # Archivos estáticos

    'nucleo',  # ← Aplicación principal de SAC WEB
]


# =============================================================================
# MIDDLEWARE
# =============================================================================
# Son capas que procesan cada solicitud antes de llegar a las vistas.
# No es necesario modificarlos para el funcionamiento básico.

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'sac_web.urls'


# =============================================================================
# CONFIGURACIÓN DE PLANTILLAS (TEMPLATES)
# =============================================================================
# Las plantillas son archivos HTML que Django procesa para mostrar páginas.
# APP_DIRS=True busca automáticamente en carpetas templates/ de cada app.

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],  # Templates globales (vacío, usamos templates por app)
        'APP_DIRS': True,  # Buscar en nucleo/templates/
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',    # Variables de debug
                'django.template.context_processors.request',  # Objeto request
                'django.contrib.auth.context_processors.auth', # Usuario actual
                'django.contrib.messages.context_processors.messages',  # Mensajes
                # Procesadores de contexto personalizados del sistema
                'nucleo.context_processors.informacion_sistema',
                'nucleo.context_processors.notificaciones_usuario',
            ],
        },
    },
]

WSGI_APPLICATION = 'sac_web.wsgi.application'


# =============================================================================
# BASE DE DATOS - SQLite
# =============================================================================
# SQLite es una base de datos simple que guarda todo en un solo archivo.
# Es ideal para desarrollo y proyectos pequeños/medianos.
# El archivo se crea automáticamente como 'db.sqlite3'.

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# =============================================================================
# VALIDACIÓN DE CONTRASEÑAS
# =============================================================================
# Reglas que Django aplica cuando un usuario crea una contraseña.

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# =============================================================================
# IDIOMA Y ZONA HORARIA
# =============================================================================
# Configuramos español de Venezuela y la zona horaria de Caracas.
# Esto afecta cómo se muestran fechas, números y el panel de admin.

LANGUAGE_CODE = 'es-ve'           # Español Venezuela
TIME_ZONE = 'America/Caracas'     # Zona horaria de Venezuela
USE_I18N = True                   # Activar internacionalización
USE_TZ = True                     # Usar zona horaria en fechas

# =============================================================================
# FORMATO DE NÚMEROS (Europeo/Venezolano: 1.000,00)
# =============================================================================
USE_THOUSAND_SEPARATOR = True
DECIMAL_SEPARATOR = ','
THOUSAND_SEPARATOR = '.'
NUMBER_GROUPING = 3


# =============================================================================
# ARCHIVOS ESTÁTICOS (CSS, JavaScript, Imágenes)
# =============================================================================
# Los archivos estáticos son CSS, JS e imágenes que no cambian.
# STATIC_URL es la ruta web (ej: /static/css/estilos.css)
# STATICFILES_DIRS indica dónde buscar los archivos en el proyecto.

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / 'static',  # Carpeta static/ en la raíz del proyecto
]


# =============================================================================
# ARCHIVOS MEDIA (Subidos por usuarios)
# =============================================================================
# Los archivos media son subidos por usuarios (ej: comprobantes de pago).
# MEDIA_URL es la ruta web para acceder a ellos.
# MEDIA_ROOT es la carpeta física donde se guardan.

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# =============================================================================
# CONFIGURACIÓN POR DEFECTO DE CAMPOS PRIMARIOS
# =============================================================================
# Tipo de campo que Django usa para IDs automáticos en los modelos.

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# =============================================================================
# CONFIGURACIÓN DE LOGIN (para autenticación de usuarios)
# =============================================================================
# Rutas donde Django redirige al usuario según su estado de sesión.

LOGIN_URL = '/login/'              # A dónde ir si no está autenticado
LOGIN_REDIRECT_URL = '/'           # A dónde ir después de hacer login
LOGOUT_REDIRECT_URL = '/login/'    # A dónde ir después de hacer logout
