# Generated by Django 6.0.1 on 2026-01-13 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatosCondominio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_condominio', models.CharField(help_text='Nombre oficial del edificio o conjunto residencial', max_length=200, verbose_name='Nombre del condominio')),
                ('rif', models.CharField(help_text='Registro de Información Fiscal del condominio', max_length=20, verbose_name='RIF del condominio')),
                ('direccion', models.TextField(help_text='Dirección completa del condominio', verbose_name='Dirección')),
                ('datos_bancarios', models.TextField(help_text='Información de la cuenta bancaria para recibir pagos', verbose_name='Datos bancarios')),
                ('contacto_admin', models.CharField(help_text='Nombre y teléfono del administrador', max_length=100, verbose_name='Contacto del administrador')),
            ],
            options={
                'verbose_name': 'Datos del Condominio',
                'verbose_name_plural': 'Datos del Condominio',
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(help_text='Formato: YYYY-MM (ej: 2026-01 para enero 2026)', max_length=7, unique=True, verbose_name='Período')),
                ('creada_en', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se creó la factura', verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'ordering': ['-periodo'],
            },
        ),
        migrations.CreateModel(
            name='Inmueble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_apto', models.CharField(help_text='Identificador único del inmueble (ej: 1A, 2B, PH-1)', max_length=10, unique=True, verbose_name='Número de apartamento')),
                ('propietario', models.CharField(blank=True, help_text='Nombre completo del propietario actual', max_length=100, null=True, verbose_name='Nombre del propietario')),
                ('alicuota', models.DecimalField(blank=True, decimal_places=8, help_text='Porcentaje de participación en gastos comunes (ej: 0.05263158)', max_digits=10, null=True, verbose_name='Alícuota')),
            ],
            options={
                'verbose_name': 'Inmueble',
                'verbose_name_plural': 'Inmuebles',
                'ordering': ['numero_apto'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del proveedor o empresa', max_length=100, verbose_name='Nombre')),
                ('rif', models.CharField(help_text='Registro de Información Fiscal (ej: J-12345678-9)', max_length=20, verbose_name='RIF')),
                ('telefono', models.CharField(blank=True, help_text='Número de contacto', max_length=20, null=True, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, help_text='Email de contacto', max_length=254, null=True, verbose_name='Correo electrónico')),
                ('direccion', models.TextField(blank=True, help_text='Dirección física del proveedor', null=True, verbose_name='Dirección')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['nombre'],
            },
        ),
    ]
