# Generated by Django 6.0.1 on 2026-01-13 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del presupuesto (ej: Presupuesto 2026)', max_length=100, verbose_name='Nombre')),
                ('anio', models.IntegerField(help_text='Año del presupuesto', verbose_name='Año')),
            ],
            options={
                'verbose_name': 'Presupuesto',
                'verbose_name_plural': 'Presupuestos',
                'ordering': ['-anio'],
            },
        ),
        migrations.CreateModel(
            name='ActividadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('CREAR', 'Crear'), ('EDITAR', 'Editar'), ('BORRAR', 'Borrar'), ('GENERAR', 'Generar')], help_text='Tipo de acción realizada', max_length=20, verbose_name='Acción')),
                ('modelo', models.CharField(help_text='Modelo afectado (ej: Factura, Pago)', max_length=50, verbose_name='Modelo')),
                ('objeto_id', models.IntegerField(help_text='ID del registro afectado', verbose_name='ID del objeto')),
                ('descripcion', models.TextField(help_text='Descripción detallada de la acción', verbose_name='Descripción')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, help_text='Momento en que se realizó la acción', verbose_name='Fecha y hora')),
                ('usuario', models.ForeignKey(help_text='Usuario que realizó la acción', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Registro de Actividad',
                'verbose_name_plural': 'Registros de Actividad',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(help_text='Descripción del gasto (ej: Servicio de limpieza)', max_length=255, verbose_name='Descripción')),
                ('monto', models.DecimalField(decimal_places=2, help_text='Monto total del gasto', max_digits=12, verbose_name='Monto')),
                ('categoria', models.CharField(choices=[('ORDINARIO', 'Ordinario'), ('IMPREVISTO', 'Imprevisto'), ('EXTRAORDINARIO', 'Extraordinario')], default='ORDINARIO', help_text='Tipo de gasto', max_length=20, verbose_name='Categoría')),
                ('es_gasto_no_comun', models.BooleanField(default=False, help_text='Marcar si solo un inmueble debe pagar este gasto', verbose_name='¿Es gasto no común?')),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to='nucleo.factura', verbose_name='Factura')),
                ('inmueble_especifico', models.ForeignKey(blank=True, help_text='Solo aplica si es gasto no común', null=True, on_delete=django.db.models.deletion.SET_NULL, to='nucleo.inmueble', verbose_name='Inmueble específico')),
            ],
            options={
                'verbose_name': 'Gasto',
                'verbose_name_plural': 'Gastos',
                'ordering': ['factura', 'descripcion'],
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leida', models.BooleanField(default=False, help_text='Indica si el usuario ya vio la notificación', verbose_name='Leída')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Momento en que se creó la notificación', verbose_name='Fecha de creación')),
                ('actividad', models.ForeignKey(help_text='Actividad que generó la notificación', on_delete=django.db.models.deletion.CASCADE, to='nucleo.actividadlog', verbose_name='Actividad')),
                ('usuario', models.ForeignKey(help_text='Usuario que recibe la notificación', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField(help_text='Fecha en que se realizó el pago', verbose_name='Fecha de pago')),
                ('monto_pagado', models.DecimalField(decimal_places=2, help_text='Cantidad pagada', max_digits=12, verbose_name='Monto pagado')),
                ('moneda', models.CharField(choices=[('BS', 'Bolívares'), ('USD', 'Dólares')], default='BS', help_text='Moneda del pago', max_length=3, verbose_name='Moneda')),
                ('tasa_cambio', models.DecimalField(blank=True, decimal_places=4, help_text='Solo si el pago es en USD', max_digits=10, null=True, verbose_name='Tasa de cambio')),
                ('metodo_pago', models.CharField(choices=[('TRANSFERENCIA', 'Transferencia bancaria'), ('PAGO_MOVIL', 'Pago móvil'), ('EFECTIVO', 'Efectivo'), ('CHEQUE', 'Cheque'), ('ZELLE', 'Zelle'), ('OTRO', 'Otro')], default='TRANSFERENCIA', max_length=20, verbose_name='Método de pago')),
                ('referencia', models.CharField(blank=True, help_text='Número de referencia de la transacción', max_length=50, null=True, verbose_name='Número de referencia')),
                ('comprobante', models.FileField(blank=True, help_text='Imagen o PDF del comprobante de pago', null=True, upload_to='comprobantes/', verbose_name='Comprobante')),
                ('notas', models.TextField(blank=True, help_text='Observaciones adicionales', null=True, verbose_name='Notas')),
                ('factura', models.ForeignKey(help_text='Factura a la que corresponde el pago', on_delete=django.db.models.deletion.CASCADE, to='nucleo.factura', verbose_name='Factura')),
                ('inmueble', models.ForeignKey(help_text='Apartamento que realiza el pago', on_delete=django.db.models.deletion.CASCADE, to='nucleo.inmueble', verbose_name='Inmueble')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-fecha_pago'],
            },
        ),
        migrations.CreateModel(
            name='PartidaPresupuestaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(help_text='Descripción de la partida (ej: Mantenimiento ascensores)', max_length=255, verbose_name='Descripción')),
                ('monto_presupuestado', models.DecimalField(decimal_places=2, help_text='Monto asignado a esta partida', max_digits=12, verbose_name='Monto presupuestado')),
                ('presupuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas', to='nucleo.presupuesto', verbose_name='Presupuesto')),
            ],
            options={
                'verbose_name': 'Partida Presupuestaria',
                'verbose_name_plural': 'Partidas Presupuestarias',
                'ordering': ['presupuesto', 'descripcion'],
            },
        ),
    ]
