# Generated by Django 6.0.1 on 2026-01-13 19:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0002_presupuesto_actividadlog_gasto_notificacion_pago_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenAccesoTemporal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(help_text='Token único generado automáticamente', max_length=64, unique=True, verbose_name='Token')),
                ('vista_destino', models.CharField(help_text='Nombre de la vista a la que da acceso', max_length=100, verbose_name='Vista destino')),
                ('parametros', models.JSONField(default=dict, help_text='Parámetros necesarios para la vista (factura_id, inmueble_id, etc.)', verbose_name='Parámetros')),
                ('usado', models.BooleanField(default=False, help_text='Indica si el token ya fue utilizado', verbose_name='Usado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_expiracion', models.DateTimeField(verbose_name='Fecha de expiración')),
                ('usuario', models.ForeignKey(help_text='Usuario que generó el token', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Token de Acceso Temporal',
                'verbose_name_plural': 'Tokens de Acceso Temporal',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
