# Generated by Django 6.0.1 on 2026-01-13 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0003_tokenaccesotemporal'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='documento_identidad',
            field=models.CharField(blank=True, help_text='R.I.F. o C.I. del propietario (ej: V-12345678, J-31215969-3)', max_length=20, null=True, verbose_name='Documento de Identidad'),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='email',
            field=models.EmailField(blank=True, help_text='Email de contacto del propietario', max_length=254, null=True, verbose_name='Correo Electrónico'),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='notas',
            field=models.TextField(blank=True, help_text='Notas o comentarios sobre el inmueble o propietario', null=True, verbose_name='Comentarios Adicionales'),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='telefono',
            field=models.CharField(blank=True, help_text='Número de teléfono del propietario (ej: 0424-232-43-85)', max_length=20, null=True, verbose_name='Teléfono de Contacto'),
        ),
    ]
