# Generated by Django 6.0.1 on 2026-01-27 15:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0004_inmueble_documento_identidad_inmueble_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta_seguridad', models.CharField(help_text='Ej: ¿Nombre de tu primera mascota?', max_length=200, verbose_name='Pregunta de Seguridad')),
                ('respuesta_seguridad', models.CharField(help_text='Respuesta para recuperar contraseña', max_length=200, verbose_name='Respuesta')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuario',
            },
        ),
    ]
