# Generated by Django 6.0.1 on 2026-02-03 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0005_perfilusuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='datoscondominio',
            name='tasa_cambio_dolar',
            field=models.DecimalField(decimal_places=4, default=1.0, help_text='Valor del dólar para cálculos referenciales', max_digits=10, verbose_name='Tasa de cambio del día (BCV)'),
        ),
    ]
