# Generated by Django 6.0.1 on 2026-02-03 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0006_datoscondominio_tasa_cambio_dolar'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='fecha_ingreso',
            field=models.DateField(blank=True, help_text='Fecha desde la cual el inmueble participa en las facturas', null=True, verbose_name='Fecha de Ingreso'),
        ),
    ]
