# Generated by Django 6.0.1 on 2026-02-07 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0007_add_fecha_ingreso_inmueble'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='numero_apto',
            field=models.CharField(help_text='Identificador único del inmueble (ej: 1A, 2B, PH-1)', max_length=50, unique=True, verbose_name='Número de apartamento'),
        ),
    ]
