# Generated by Django 6.0.1 on 2026-04-15 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0008_alter_inmueble_numero_apto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='respuesta_seguridad',
            field=models.CharField(help_text='Hash de la respuesta para recuperar contraseña', max_length=255, verbose_name='Respuesta (Hashed)'),
        ),
    ]
