# Generated by Django 6.0.1 on 2026-08-31 18:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0009_alter_perfilusuario_respuesta_seguridad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='comprobante',
            field=models.FileField(blank=True, help_text='Imagen o PDF del comprobante de pago', null=True, upload_to='comprobantes/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'pdf'])], verbose_name='Comprobante'),
        ),
    ]
